window.PRODUCTS = [
  {
    "id": 3402,
    "slug": "125er",
    "name": "125er",
    "fullName": "125er Elektroroller",
    "category": "Highspeed & 125er",
    "price": 2966,
    "speed": null,
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/125er?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3171,
    "slug": "raven",
    "name": "Raven",
    "fullName": "E-Chopper Raven, 45 km/h, 60 V / 40 Ah",
    "category": "E-Chopper",
    "price": 2799,
    "speed": "45 km/h",
    "range": "bis zu 100 km",
    "power": "bis zu 3.000 W",
    "battery": "60 V / 40 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/9/7/7/8/19778.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-raven?affp=17205#/farbe-light_grey/anzahl_lithium_ionen_akkus-60v_40ah_100km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1801,
    "slug": "angry-blake",
    "name": "Angry Blake",
    "fullName": "E-Chopper Angry Blake mit Samsung-Lithium-Akku",
    "category": "E-Chopper",
    "price": 3999,
    "speed": "86 km/h",
    "range": null,
    "power": null,
    "battery": "Samsung-Lithium-Akku",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-x10?affp=17205#/farbe-schwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1867,
    "slug": "blake",
    "name": "Blake",
    "fullName": "E-Chopper Blake, 45 km/h, 60 V / 40 Ah",
    "category": "E-Chopper",
    "price": 2999,
    "speed": "45 km/h",
    "range": "bis zu 100 km",
    "power": "bis zu 3.000 W",
    "battery": "60 V / 40 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/2/9/0/1/12901.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-blake?affp=17205#/farbe-light_grey/anzahl_lithium_ionen_akkus-60v_40ah_100km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3593,
    "slug": "hl-6-premium-duo",
    "name": "HL 6.0 Premium Duo",
    "fullName": "E-Chopper HL 6.0 Premium Duo für zwei Personen",
    "category": "E-Chopper",
    "price": 3499,
    "speed": "45 km/h",
    "range": "bis zu 120 km",
    "power": "3.000 W",
    "battery": "56 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/6/8/7/9/16879.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-6-premium-duo?affp=17205#/farbe-mattschwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 2984,
    "slug": "hl-6-premium",
    "name": "HL 6.0 Premium",
    "fullName": "E-Chopper HL 6.0 Premium mit TFT-Display",
    "category": "E-Chopper",
    "price": 3499,
    "speed": "45 km/h",
    "range": "bis zu 120 km",
    "power": "3.000 W",
    "battery": "60 V / 56,5 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/6/8/7/9/16879.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-6-premium?affp=17205#/farbe-mattschwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1000,
    "slug": "hl-6",
    "name": "HL 6.0",
    "fullName": "E-Chopper HL 6.0 mit 30-Ah-Akku",
    "category": "E-Chopper",
    "price": 2899,
    "speed": "45 km/h",
    "range": "bis zu 70 km",
    "power": "3.000 W",
    "battery": "60 V / 30 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-11?affp=17205#/farbe-bordeaux_rot/geschwindigkeit_auswahlen-45_km_h",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3214,
    "slug": "hl-6-android",
    "name": "HL 6.0 Android",
    "fullName": "E-Chopper HL 6.0 mit 7-Zoll-Touch-Display und Navigation",
    "category": "E-Chopper",
    "price": 3599,
    "speed": "45 km/h",
    "range": null,
    "power": "3.000 W",
    "battery": "60 V / 55 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-6-android?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h/lithium_akku_-hl_60_55ah_60v_lithium_akku",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1382,
    "slug": "futura-two-li",
    "name": "FUTURA TWO Li",
    "fullName": "Vier­rädriger E-Kabinenroller FUTURA TWO Li mit Lenker oder Lenkrad",
    "category": "Kabinenroller",
    "price": 6999,
    "speed": "45 km/h",
    "range": "bis zu 60 / 120 km",
    "power": "bis zu 2.000 W",
    "battery": "60 V / 52 Ah Lithium, entnehmbar",
    "image": "https://elektroroller-futura.de/12413-home_default_2x/elektro-kabinenroller-two.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/futura-two-futura-30",
    "sourceLabel": "Elektroroller Futura",
    "sourceUrl": "https://elektroroller-futura.de/futura-two-futura-30",
    "recommendation": "Spannend, wenn du vier Räder, zwei Sitze und einen herausnehmbaren Akku suchst.",
    "caveat": "Mit 1,07 Meter Breite und Rückbank anders zu fahren als ein klassischer Roller – Probefahrt einplanen.",
    "verifiedAt": "September 2026",
    "isAffiliate": false,
    "offerLabel": "Modellübersicht"
  },
  {
    "id": 2897,
    "slug": "mars",
    "name": "Mars",
    "fullName": "E-Motorrad Mars",
    "category": "E-Motorrad & Enduro",
    "price": 3999,
    "speed": "100 km/h",
    "range": null,
    "power": "6.000 W",
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-e-motorrad-mars?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3622,
    "slug": "campster",
    "name": "Campster",
    "fullName": "E-Roller Campster für Wohnmobil und kurze Wege",
    "category": "E-Roller",
    "price": 999,
    "speed": "25 km/h",
    "range": "bis zu 50 km",
    "power": "800 W",
    "battery": "48 V / 20 Ah Blei-Gel",
    "image": "https://elektroroller-futura.de/img/p/2/0/0/8/7/20087.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-campster-25-kmh-wohnmobil?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 2501,
    "slug": "city-go",
    "name": "City Go",
    "fullName": "E-Roller City Go mit CarPlay",
    "category": "E-Roller",
    "price": 1999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 90 km",
    "power": "1.200 W",
    "battery": "48 V / 30 Ah LiFePO₄",
    "image": "https://elektroroller-futura.de/img/p/1/9/1/0/2/19102.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-merlin?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 86,
    "slug": "falcon-double",
    "name": "Falcon Double",
    "fullName": "E-Roller Falcon Double mit Lithium-Akku",
    "category": "E-Roller",
    "price": 2399,
    "speed": "25 / 45 km/h",
    "range": "bis zu 80 km je Akku",
    "power": "bis zu 3.400 W",
    "battery": "72 V / 20 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/2/2/8/6/2286.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-falcon?affp=17205#/geschwindigkeit_auswahlen-45_km_h/farbe-schwarz/anzahl_lithium_ionen_akkus-1_lithium_akku_80_km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 2912,
    "slug": "falcon-double-max-range",
    "name": "Falcon Double Max Range",
    "fullName": "E-Roller Falcon Double Max Range",
    "category": "E-Roller",
    "price": 2499,
    "speed": "45 km/h",
    "range": "bis zu 100 km",
    "power": "3.400 W",
    "battery": "72 V / 30 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/2/2/8/6/2286.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-falcon-30ah?affp=17205#/farbe-schwarz/anzahl_lithium_ionen_akkus-1_lithium_akku_100_km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3399,
    "slug": "future-s",
    "name": "FUTURE-S",
    "fullName": "E-Roller FUTURE-S",
    "category": "Highspeed & 125er",
    "price": 3699,
    "speed": "80 km/h",
    "range": null,
    "power": "4.000 W",
    "battery": "72 V / 50 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-future-s?affp=17205#/farbe-gelb",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 2634,
    "slug": "future",
    "name": "Future",
    "fullName": "E-Roller Future mit Lithium-Akku",
    "category": "E-Roller",
    "price": 2499,
    "speed": "45 km/h",
    "range": "bis zu 90 km",
    "power": "3.000 W",
    "battery": "72 V / 26 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/8/8/1/0/18810.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-future?affp=17205#/geschwindigkeit_auswahlen-45_km_h/farbe-gelb",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3566,
    "slug": "long-runner-blei",
    "name": "Long Runner Blei",
    "fullName": "E-Roller Long Runner mit Blei-Gel-Akku",
    "category": "E-Roller",
    "price": 1699,
    "speed": "25 km/h",
    "range": "bis zu 85 km",
    "power": null,
    "battery": "60 V / 32 Ah Blei-Gel",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-long-runner-blei?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-25_km_h",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 2889,
    "slug": "long-runner-lithium",
    "name": "Long Runner Lithium",
    "fullName": "E-Roller Long Runner mit Samsung-Lithium-Akku",
    "category": "E-Roller",
    "price": 1999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 80 km",
    "power": "bis zu 2.800 W",
    "battery": "60 V / 30 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/7/2/8/9/17289.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-long-runner?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h/anzahl_lithium_ionen_akkus-1_x_li_akku_60v_30ah_80_km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3587,
    "slug": "volt-max",
    "name": "Volt-Max",
    "fullName": "E-Roller Volt-Max mit Lithium-Akku",
    "category": "E-Roller",
    "price": 2399,
    "speed": "25 / 45 km/h",
    "range": "bis zu 80 km",
    "power": "3.400 W",
    "battery": "72 V / 20 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/volt-max?affp=17205#/farbe-grun/geschwindigkeit_auswahlen-45_km_h/anzahl_lithium_ionen_akkus-1_lithium_akku_80_km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1293,
    "slug": "e-groove",
    "name": "E-Groove",
    "fullName": "E-Scooter E-Groove mit deutscher Straßenzulassung",
    "category": "E-Scooter",
    "price": 999,
    "speed": "25 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-power?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3090,
    "slug": "m300-eec",
    "name": "M300 EEC",
    "fullName": "Elektro Enduro M300 EEC mit Straßenzulassung",
    "category": "E-Motorrad & Enduro",
    "price": 3999,
    "speed": null,
    "range": null,
    "power": "6.000 W",
    "battery": "72 V / 34 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektro-enduro-strassenzulassung?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3417,
    "slug": "volt-ranger",
    "name": "Volt Ranger",
    "fullName": "Elektro Quad Volt Ranger mit Straßenzulassung",
    "category": "Quad",
    "price": 2399,
    "speed": "45 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/volt-ranger?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1156,
    "slug": "classico-highspeed",
    "name": "Classico Highspeed",
    "fullName": "Elektroroller Classico Highspeed",
    "category": "Highspeed & 125er",
    "price": 3699,
    "speed": "80 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-classico-li-highspeed?affp=17205#/farbe-blue",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 10,
    "slug": "classico-li",
    "name": "Classico Li",
    "fullName": "Elektroroller Classico Li mit Windschild",
    "category": "E-Roller",
    "price": 2399,
    "speed": "25 / 45 km/h",
    "range": "bis zu 60 km je Akku",
    "power": "3.000 W",
    "battery": "72 V / 20 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/8/6/3/7/8637.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-classico-li?affp=17205#/geschwindigkeit_auswahlen-45_km_h/farbe-rot/anzahl_lithium_ionen_akkus-1_lithium_ionen_akku_60km_reichweite_000_",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 367,
    "slug": "falcon-blei",
    "name": "Falcon Blei",
    "fullName": "Elektroroller Falcon mit Blei-Gel-Akku",
    "category": "E-Roller",
    "price": 1599,
    "speed": null,
    "range": null,
    "power": "3.400 W",
    "battery": "Blei-Gel",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-kaufen-falcon-2?affp=17205#/farbe-schwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 20,
    "slug": "futura-hawk",
    "name": "FUTURA HAWK",
    "fullName": "Elektroroller Futura HAWK mit Blei-Gel-Akku",
    "category": "E-Roller",
    "price": 1699,
    "speed": "45 km/h",
    "range": null,
    "power": null,
    "battery": "Blei-Gel",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-hawk-blei-gel-akku?affp=17205#/farbe-mattschwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 1275,
    "slug": "hl-6-sale",
    "name": "HL 6.0 Sale",
    "fullName": "E-Chopper HL 6.0",
    "category": "E-Chopper",
    "price": 2799,
    "speed": "45 km/h",
    "range": null,
    "power": "3.000 W",
    "battery": "60 V / 30 Ah Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-6?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h/lithium_akku_-hl_60_30ah_60v_lithium_akku",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3233,
    "slug": "thunder-s",
    "name": "THUNDER-S",
    "fullName": "E-Motorrad THUNDER-S",
    "category": "E-Motorrad & Enduro",
    "price": 2699,
    "speed": "80 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/thunder?affp=17205#/farbe-light_grey",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 417,
    "slug": "angry-hawk",
    "name": "ANGRY HAWK",
    "fullName": "E-Roller Futura ANGRY HAWK",
    "category": "Highspeed & 125er",
    "price": 3499,
    "speed": "80 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-e-motorrad?affp=17205#/farbe-light_grey",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3203,
    "slug": "city-go-rs",
    "name": "City Go RS",
    "fullName": "E-Roller City Go RS",
    "category": "E-Roller",
    "price": 1999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 90 km",
    "power": null,
    "battery": "30 Ah",
    "image": "https://elektroroller-futura.de/img/p/1/9/1/0/2/19102.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-merlin?affp=17205#/farbe-bordeaux_rot/geschwindigkeit_auswahlen-45_km_h",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 266,
    "slug": "robo-s",
    "name": "ROBO-S",
    "fullName": "Elektroroller ROBO-S",
    "category": "Highspeed & 125er",
    "price": 4500,
    "speed": "80 km/h",
    "range": null,
    "power": null,
    "battery": null,
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-robo-s?affp=17205#/farbe-schwarz",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 87,
    "slug": "eagle",
    "name": "Eagle",
    "fullName": "Elektroroller Eagle mit Blei-Gel-Akku",
    "category": "E-Roller",
    "price": 1599,
    "speed": "45 km/h",
    "range": null,
    "power": "2.000 W",
    "battery": "Blei-Gel",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/eagle-one",
    "isAffiliate": false,
    "offerLabel": "Modellübersicht",
    "sourceUrl": "https://elektroroller-futura.de/eagle-one"
  },
  {
    "id": 1324,
    "slug": "x9-plus-30ah",
    "name": "X9 Plus 30 Ah",
    "fullName": "E-Chopper X9 Plus mit 30-Ah-Lithium-Akku",
    "category": "E-Chopper",
    "price": 2299,
    "speed": "45 km/h",
    "range": "bis zu 75 km",
    "power": "3.000 W",
    "battery": "60 V / 30 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/8/1/0/9/18109.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-x9-30ah?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h/anzahl_lithium_ionen_akkus-60v_30ah_75km_reichweite",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 3247,
    "slug": "x9-plus-20ah",
    "name": "X9 Plus 20 Ah",
    "fullName": "E-Chopper X9 Plus mit 20-Ah-Lithium-Akku",
    "category": "E-Chopper",
    "price": 1999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 50 km",
    "power": "bis zu 3.000 W",
    "battery": "60 V / 20 Ah Lithium",
    "image": "https://elektroroller-futura.de/img/p/1/8/1/0/9/18109.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/e-scooter-chopper-x9-20?affp=17205",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 131,
    "slug": "eagle-li",
    "name": "Eagle Li",
    "fullName": "E-Roller Eagle Li mit Lithium-Akku",
    "category": "E-Roller",
    "price": 1999,
    "speed": null,
    "range": null,
    "power": "2.000 W",
    "battery": "Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/eagle-one",
    "isAffiliate": false,
    "offerLabel": "Modellübersicht",
    "sourceUrl": "https://elektroroller-futura.de/eagle-one"
  },
  {
    "id": 402,
    "slug": "hawk-2",
    "name": "HAWK 2.0",
    "fullName": "Elektroroller HAWK 2.0 mit Lithium-Akku",
    "category": "E-Roller",
    "price": 2399,
    "speed": "45 km/h",
    "range": "bis zu 60 km",
    "power": "3.000 W",
    "battery": "Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-hawk-2?affp=17205#/farbe-mattschwarz/geschwindigkeit_auswahlen-45_km_h/anzahl_lithium_ionen_akkus-1_lithium_ionen_akku_60km_reichweite_000_",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 667,
    "slug": "elettrico-2",
    "name": "Elettrico 2.0",
    "fullName": "E-Roller Elettrico 2.0",
    "category": "E-Roller",
    "price": 2199,
    "speed": "25 / 45 km/h",
    "range": "bis zu 60 km",
    "power": null,
    "battery": "Lithium",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektroroller/elektroroller-elettrico-2?affp=17205#/geschwindigkeit_auswahlen-45_km_h/farbe-weiss/anzahl_lithium_ionen_akkus-1_lithium_ionen_akku_60km_reichweite_000_",
    "isAffiliate": true,
    "offerLabel": "Angebot"
  },
  {
    "id": 4101,
    "slug": "futura-3-li",
    "name": "Futura 3.0 Li",
    "fullName": "Dreirädriger E-Kabinenroller mit herausnehmbarem Lithium-Akku",
    "category": "Kabinenroller",
    "price": 6999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 70 / 140 km",
    "power": "2.000 W",
    "battery": "60 V / 52 Ah Lithium, entnehmbar",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/futura-two-futura-30",
    "sourceLabel": "Elektroroller Futura",
    "sourceUrl": "https://elektroroller-futura.de/futura-two-futura-30",
    "recommendation": "Guter Kandidat, wenn der Akku zum Laden aus dem Fahrzeug mitkommen muss.",
    "caveat": "Drei Räder und hoher Aufbau verlangen eine besonders bewusste Probefahrt.",
    "verifiedAt": "September 2026",
    "isAffiliate": false,
    "offerLabel": "Modellübersicht"
  },
  {
    "id": 4102,
    "slug": "cruise-li",
    "name": "Cruise Li",
    "fullName": "Kabinenroller mit drehbarem Sitz und bis zu zwei Lithium-Akkus",
    "category": "Kabinenroller",
    "price": 6999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 70 / 140 km",
    "power": "2.200 W",
    "battery": "60 V / 60 Ah Lithium, entnehmbar",
    "image": "https://elektroroller-futura.de/15715-big_default/elektro-kabinenroller-cruise-li.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektromobilitaet-fuer-senioren/elektro-kabinenroller-cruise-li",
    "sourceLabel": "Elektroroller Futura",
    "sourceUrl": "https://elektroroller-futura.de/shop/elektromobilitaet-fuer-senioren/elektro-kabinenroller-cruise-li",
    "recommendation": "Besonders interessant, wenn Einstieg, Handbedienung und Reichweitenoptionen zählen.",
    "caveat": "Zweitakku, Ausstattung und tatsächliche Lieferkonfiguration vor dem Kauf genau abgleichen.",
    "verifiedAt": "September 2026",
    "isAffiliate": false,
    "offerLabel": "Angebot"
  },
  {
    "id": 4103,
    "slug": "e-move",
    "name": "E-Move",
    "fullName": "Preisorientierter Kabinenroller mit zwei Sitzen und Blei-Gel-Akku",
    "category": "Kabinenroller",
    "price": 3499,
    "speed": "25 / 45 km/h",
    "range": "bis zu 70 km",
    "power": "2.000 W",
    "battery": "60 V / 45 Ah Blei-Gel",
    "image": null,
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektromobilitaet-fuer-senioren/elektro-kabinenroller-e-move",
    "sourceLabel": "Elektroroller Futura",
    "sourceUrl": "https://elektroroller-futura.de/shop/elektromobilitaet-fuer-senioren/elektro-kabinenroller-e-move",
    "recommendation": "Der Preis-Einstieg für kurze Alltagswege mit Wetterschutz und zwei Sitzplätzen.",
    "caveat": "Der feste Blei-Gel-Akku braucht einen geeigneten Stellplatz mit erreichbarer Steckdose.",
    "verifiedAt": "September 2026",
    "isAffiliate": false,
    "offerLabel": "Angebot"
  },
  {
    "id": 4104,
    "slug": "limaq7-li",
    "name": "LimaQ7 Li",
    "fullName": "Geräumiger E-Kabinenroller mit herausnehmbarem 72-Volt-Lithium-Akku",
    "category": "Kabinenroller",
    "price": 6999,
    "speed": "25 / 45 km/h",
    "range": "bis zu 70 km",
    "power": "3.000 W",
    "battery": "72 V / 55 Ah Lithium, entnehmbar",
    "image": "https://elektroroller-futura.de/19820-thickbox_default/kabinenroller-limaq7-li-45-kmh-lithium-akku-3000-watt.jpg",
    "affiliateUrl": "https://elektroroller-futura.de/shop/elektro-kabinenroller-futura/kabinenroller-limaq7-li-45-kmh-lithium-akku-3000-watt",
    "sourceLabel": "Elektroroller Futura",
    "sourceUrl": "https://elektroroller-futura.de/shop/elektro-kabinenroller-futura/kabinenroller-limaq7-li-45-kmh-lithium-akku-3000-watt",
    "recommendation": "Für alle, die mehr Kabinenbreite und einen entnehmbaren Akku priorisieren.",
    "caveat": "Mit rund 1,25 Meter Breite vorher Stellplatz, Toreinfahrt und typische Wege ausmessen.",
    "verifiedAt": "September 2026",
    "isAffiliate": false,
    "offerLabel": "Angebot"
  }
];
